//! Bounded fail-open cache primitives for Soroban RPC state reads.
//!
//! The crate has no networking or Kubernetes dependencies, so it can be compiled
//! as a small Wasm module or embedded by a host-side RPC adapter. Cache failures
//! are represented as `CacheError`; callers must use the underlying RPC result
//! when handling those errors.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
#[cfg(not(target_arch = "wasm32"))]
use std::time::{Duration, Instant};

#[cfg(not(target_arch = "wasm32"))]
type CacheTimestamp = Instant;
#[cfg(target_arch = "wasm32")]
type CacheTimestamp = f64;

#[cfg(not(target_arch = "wasm32"))]
fn cache_now() -> CacheTimestamp {
    Instant::now()
}

#[cfg(target_arch = "wasm32")]
fn cache_now() -> CacheTimestamp {
    js_sys::Date::now()
}

fn cache_expired(inserted_at: &CacheTimestamp, ttl_secs: u64) -> bool {
    #[cfg(not(target_arch = "wasm32"))]
    {
        Instant::now().duration_since(*inserted_at) >= Duration::from_secs(ttl_secs)
    }

    #[cfg(target_arch = "wasm32")]
    {
        cache_now() - *inserted_at >= ttl_secs as f64 * 1000.0
    }
}

/// Conservative defaults suitable for a small sidecar sandbox.
pub const DEFAULT_TTL_SECS: u64 = 30;
pub const DEFAULT_MAX_ENTRIES: usize = 10_000;
pub const DEFAULT_MAX_BYTES: usize = 64 * 1024 * 1024;
/// Hard upper bounds keep configuration from exceeding the sandbox budget.
pub const MAX_CACHE_ENTRIES: usize = DEFAULT_MAX_ENTRIES;
pub const MAX_CACHE_BYTES: usize = DEFAULT_MAX_BYTES;

/// Runtime cache settings. These fields map directly to ConfigMap keys.
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct CacheConfig {
    #[serde(default = "default_ttl_secs")]
    pub ttl_secs: u64,
    #[serde(default = "default_max_entries")]
    pub max_entries: usize,
    #[serde(default = "default_max_bytes")]
    pub max_bytes: usize,
}

fn default_ttl_secs() -> u64 {
    DEFAULT_TTL_SECS
}

fn default_max_entries() -> usize {
    DEFAULT_MAX_ENTRIES
}

fn default_max_bytes() -> usize {
    DEFAULT_MAX_BYTES
}

impl Default for CacheConfig {
    fn default() -> Self {
        Self {
            ttl_secs: DEFAULT_TTL_SECS,
            max_entries: DEFAULT_MAX_ENTRIES,
            max_bytes: DEFAULT_MAX_BYTES,
        }
    }
}

impl CacheConfig {
    /// Reject unsafe or unusable limits before the cache is constructed.
    pub fn validate(&self) -> Result<(), CacheError> {
        if self.ttl_secs == 0 {
            return Err(CacheError::InvalidConfig(
                "ttl_secs must be greater than zero",
            ));
        }
        if self.max_entries == 0 {
            return Err(CacheError::InvalidConfig(
                "max_entries must be greater than zero",
            ));
        }
        if self.max_bytes == 0 {
            return Err(CacheError::InvalidConfig(
                "max_bytes must be greater than zero",
            ));
        }
        if self.max_entries > MAX_CACHE_ENTRIES {
            return Err(CacheError::InvalidConfig(
                "max_entries exceeds the sandbox limit",
            ));
        }
        if self.max_bytes > MAX_CACHE_BYTES {
            return Err(CacheError::InvalidConfig(
                "max_bytes exceeds the sandbox limit",
            ));
        }
        Ok(())
    }
}

/// Errors generated by cache bookkeeping. They are intentionally separate from
/// upstream RPC errors so the caller can always fall back to the RPC request.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CacheError {
    InvalidConfig(&'static str),
    KeySerialization,
    EntryTooLarge { size: usize, max_bytes: usize },
}

#[derive(Clone, Debug)]
struct Entry {
    value: Vec<u8>,
    size: usize,
    inserted_at: CacheTimestamp,
    last_used: u64,
}

/// Observable cache counters for metrics and load-test assertions.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct CacheStats {
    pub hits: u64,
    pub misses: u64,
    pub expired: u64,
    pub evictions: u64,
    pub bypasses: u64,
    pub stored_bytes: usize,
    pub entries: usize,
}

/// A strictly bounded TTL/LRU cache.
pub struct StateCache {
    config: CacheConfig,
    entries: HashMap<String, Entry>,
    stored_bytes: usize,
    clock: u64,
    stats: CacheStats,
}

impl StateCache {
    pub fn new(config: CacheConfig) -> Result<Self, CacheError> {
        config.validate()?;
        Ok(Self {
            config,
            entries: HashMap::new(),
            stored_bytes: 0,
            clock: 0,
            stats: CacheStats::default(),
        })
    }

    /// Build the canonical cache key from the JSON-RPC method and params.
    /// Object keys are sorted recursively so equivalent requests share entries.
    pub fn request_key(method: &str, params: &Value) -> Result<String, CacheError> {
        let canonical = canonicalize(params);
        serde_json::to_string(&(method, canonical)).map_err(|_| CacheError::KeySerialization)
    }

    pub fn get(&mut self, key: &str) -> Option<Vec<u8>> {
        self.clock = self.clock.wrapping_add(1);
        let expired = self
            .entries
            .get(key)
            .map(|entry| cache_expired(&entry.inserted_at, self.config.ttl_secs))
            .unwrap_or(false);

        if expired {
            self.remove(key);
            self.stats.expired += 1;
            self.stats.misses += 1;
            return None;
        }

        if let Some(entry) = self.entries.get_mut(key) {
            entry.last_used = self.clock;
            self.stats.hits += 1;
            return Some(entry.value.clone());
        }

        self.stats.misses += 1;
        None
    }

    /// Store a response. An individual response larger than the configured
    /// budget is bypassed rather than partially stored or causing a panic.
    pub fn insert(&mut self, key: String, value: Vec<u8>) -> Result<(), CacheError> {
        let entry_size = key.len().saturating_add(value.len());
        if entry_size > self.config.max_bytes {
            self.stats.bypasses += 1;
            return Err(CacheError::EntryTooLarge {
                size: entry_size,
                max_bytes: self.config.max_bytes,
            });
        }

        self.clock = self.clock.wrapping_add(1);
        if let Some(previous) = self.entries.remove(&key) {
            self.stored_bytes = self.stored_bytes.saturating_sub(previous.size);
        }

        while self.entries.len() >= self.config.max_entries
            || self.stored_bytes.saturating_add(entry_size) > self.config.max_bytes
        {
            let oldest = self
                .entries
                .iter()
                .min_by_key(|(_, entry)| entry.last_used)
                .map(|(key, _)| key.clone());
            match oldest {
                Some(oldest) => {
                    self.remove(&oldest);
                    self.stats.evictions += 1;
                }
                None => break,
            }
        }

        self.stored_bytes = self.stored_bytes.saturating_add(entry_size);
        self.entries.insert(
            key,
            Entry {
                value,
                size: entry_size,
                inserted_at: cache_now(),
                last_used: self.clock,
            },
        );
        Ok(())
    }

    pub fn stats(&self) -> CacheStats {
        let mut stats = self.stats.clone();
        stats.stored_bytes = self.stored_bytes;
        stats.entries = self.entries.len();
        stats
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    fn remove(&mut self, key: &str) -> Option<Entry> {
        let removed = self.entries.remove(key);
        if let Some(entry) = &removed {
            self.stored_bytes = self.stored_bytes.saturating_sub(entry.size);
        }
        removed
    }
}

/// Canonicalize JSON objects recursively while preserving array order.
fn canonicalize(value: &Value) -> Value {
    match value {
        Value::Object(object) => {
            let mut sorted = serde_json::Map::new();
            let mut keys: Vec<_> = object.keys().collect();
            keys.sort_unstable();
            for key in keys {
                sorted.insert(key.clone(), canonicalize(&object[key]));
            }
            Value::Object(sorted)
        }
        Value::Array(values) => Value::Array(values.iter().map(canonicalize).collect()),
        other => other.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::thread;

    fn config() -> CacheConfig {
        CacheConfig {
            ttl_secs: 1,
            max_entries: 2,
            max_bytes: 10,
        }
    }

    #[test]
    fn canonical_keys_ignore_object_order() {
        let first = serde_json::json!({"b": 2, "a": {"d": 4, "c": 3}});
        let second = serde_json::json!({"a": {"c": 3, "d": 4}, "b": 2});
        assert_eq!(
            StateCache::request_key("getLedgerEntries", &first).unwrap(),
            StateCache::request_key("getLedgerEntries", &second).unwrap()
        );
    }

    #[test]
    fn expires_entries_after_ttl() {
        let mut cache = StateCache::new(config()).unwrap();
        cache.insert("key".into(), b"value".to_vec()).unwrap();
        thread::sleep(std::time::Duration::from_millis(1_050));
        assert_eq!(cache.get("key"), None);
        assert_eq!(cache.stats().expired, 1);
    }

    #[test]
    fn evicts_least_recently_used_entry_and_respects_bytes() {
        let mut cache = StateCache::new(config()).unwrap();
        cache.insert("a".into(), b"1234".to_vec()).unwrap();
        cache.insert("b".into(), b"5678".to_vec()).unwrap();
        assert_eq!(cache.get("a"), Some(b"1234".to_vec()));
        cache.insert("c".into(), b"zzzz".to_vec()).unwrap();
        assert_eq!(cache.get("a"), Some(b"1234".to_vec()));
        assert_eq!(cache.get("b"), None);
        assert_eq!(cache.stats().stored_bytes, 10);
    }

    #[test]
    fn ten_thousand_reads_are_served_from_bounded_cache() {
        let mut cache = StateCache::new(CacheConfig {
            ttl_secs: 60,
            max_entries: 100,
            max_bytes: 16 * 1024,
        })
        .unwrap();
        let mut upstream_reads = 0;
        for index in 0..10_000u32 {
            let key = format!("read-{}", index % 100);
            if cache.get(&key).is_none() {
                upstream_reads += 1;
                cache.insert(key, b"rpc-response".to_vec()).unwrap();
            }
        }
        assert_eq!(upstream_reads, 100);
        assert_eq!(cache.stats().hits, 9_900);
        assert!(cache.stats().stored_bytes <= 16 * 1024);
    }

    #[test]
    fn oversized_entries_fail_open_without_mutating_cache() {
        let mut cache = StateCache::new(config()).unwrap();
        let result = cache.insert("large".into(), vec![0; 6]);
        assert!(matches!(result, Err(CacheError::EntryTooLarge { .. })));
        assert!(cache.is_empty());
        assert_eq!(cache.stats().bypasses, 1);
    }

    #[test]
    fn invalid_limits_are_rejected() {
        let zero_bytes = StateCache::new(CacheConfig {
            max_bytes: 0,
            ..CacheConfig::default()
        });
        assert!(matches!(zero_bytes, Err(CacheError::InvalidConfig(_))));

        let excessive_bytes = StateCache::new(CacheConfig {
            max_bytes: MAX_CACHE_BYTES + 1,
            ..CacheConfig::default()
        });
        assert!(matches!(excessive_bytes, Err(CacheError::InvalidConfig(_))));
    }
}
