{{- if and (eq .Values.nodeType "Validator") .Values.seedSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.seedSecret.name | quote }}
  labels:
    app.kubernetes.io/name: stellar-node-gitops
    app.kubernetes.io/part-of: stellar-k8s
    stellar.org/gitops-version: v1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  {{ .Values.seedSecret.key }}: {{ .Values.seedSecret.value | quote }}
{{- end }}
