[package]
name = "gov-queue"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "On-Chain Governance Execution Queue & Proposal Registry for Stellar-K8s"
repository = "https://github.com/agnesnaomiolim-cloud/Stellar-K8s"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { version = "21.7.1", features = ["alloc"] }

[dev-dependencies]
soroban-sdk = { version = "21.7.1", features = ["testutils", "alloc"] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
